### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by alexgarciab** [alebeta90/behindflare#1]
Hi there, I am trying to execute the "behindflare" file but it is giving me this error:

`-bash: ./behindflare: can't execute binary file: Exec format error`

Is there something specific that I should do to execute the file?

**Comment by alebeta90** [comment]
Hola Alex,

Could you describe the environment where you are running behind flare?

Golang version and OS arch would be enough

Thanks

**Comment by alexgarciab** [comment]
Golang version: go version go1.15 darwin/amd64
OS: Mac OS X Catalina - 10.15.6

**Comment by alebeta90** [comment]
Hi Alex,

sorry for the delay.

you need to build the binary in your computer

`go build` and it should deliver a new binary `behindflare`

the binary in the repository was compiled for linux amd64

Let me know if it help you to solve the problem

all the best
